# Generated by Django 6.0.1 on 2026-01-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='General Education or Technical Education', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The year the exam was written (e.g., 2024)')),
                ('paper_number', models.CharField(choices=[('1', 'Paper 1 (MCQ)'), ('2', 'Paper 2 (Essay/Problem Solving)'), ('3', 'Paper 3 (Practical)')], help_text='The specific paper number (1, 2, or 3)', max_length=1)),
                ('file', models.FileField(upload_to='past_papers/')),
                ('marking_scheme_file', models.FileField(blank=True, null=True, upload_to='marking_schemes/')),
            ],
            options={
                'ordering': ['-year', 'subject__name', 'paper_number'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Ordinary Level (O/L) , Advanced Level (A/L) , ITVEE , ATVEE', max_length=50, unique=True)),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='papers.educationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='papers.level')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.pastpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g., 0570 for Mathematics', max_length=10, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='papers.level')),
            ],
            options={
                'unique_together': {('name', 'level', 'department')},
            },
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='papers.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='pastpaper',
            unique_together={('subject', 'year', 'paper_number')},
        ),
    ]
