# Generated by Django 6.0.1 on 2026-01-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(upload_to='media/past_papers/'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='marking_scheme_file',
            field=models.FileField(blank=True, null=True, upload_to='media/marking_schemes/'),
        ),
    ]
