# Generated by Django 6.0.1 on 2026-01-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_pastpaper_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'level')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ManyToManyField(blank=True, to='papers.department'),
        ),
    ]
